name: Update LinkedIn

on:
  workflow_dispatch:
  push:

jobs:
  update-linkedin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install jsonresume-to-linkedin
        run: |
          pip3 install git+https://github.com/mbund/jsonresume-to-linkedin.git

      - name: Tunnel through home tailscale
        env:
          TS_AUTHKEY: ${{ secrets.TS_AUTHKEY }}
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          tailscale up --authkey $TS_AUTHKEY --exit-node=phantasien --hostname=github-action-tunnel

      - name: Update LinkedIn
        env:
          LINKEDIN_USERNAME: ${{ secrets.LINKEDIN_USERNAME }}
          LINKEDIN_PASSWORD: ${{ secrets.LINKEDIN_PASSWORD }}
        run: |
          jsonresume-to-linkedin
