name: Render Documents

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - src/**
      - public/**

permissions:
  contents: write

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Install Chromium
        run: |
          sudo snap install chromium

      - name: Install Source Code Pro font
        run: |
          mkdir -p ~/.local/share/fonts/adobe-fonts/source-code-pro
          git clone --branch release --depth 1 https://github.com/adobe-fonts/source-code-pro ~/.local/share/fonts/adobe-fonts/source-code-pro
          fc-cache -f -v $FONT_HOME/adobe-fonts/source-code-pro

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true

      - name: Build site
        run: |
          pnpm build

      - name: Run server and render documents
        run: |
          pnpm preview &
          sleep 10
          chromium --headless --disable-gpu --print-to-pdf=resume-mark-bundschuh-$(date --iso-8601).pdf --no-margins http://localhost:3000/en/resume
          chromium --headless --disable-gpu --print-to-pdf=business-card-front-mark-bundschuh-$(date --iso-8601).pdf --no-margins http://localhost:3000/en/card/front
          chromium --headless --disable-gpu --print-to-pdf=business-card-back-mark-bundschuh-$(date --iso-8601).pdf --no-margins http://localhost:3000/en/card/back
          chromium --headless --disable-gpu --print-to-pdf=lebenslauf-mark-bundschuh-$(date --iso-8601).pdf --no-margins http://localhost:3000/de/resume
          chromium --headless --disable-gpu --print-to-pdf=visitenkarte-vorderseite-mark-bundschuh-$(date --iso-8601).pdf --no-margins http://localhost:3000/de/card/front
          chromium --headless --disable-gpu --print-to-pdf=visitenkarte-rueckseite-mark-bundschuh-$(date --iso-8601).pdf --no-margins http://localhost:3000/de/card/back
          kill %1

      - name: Get tag name
        id: tag-name
        run: |
          echo "tagname=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Upload documents
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create ${{ steps.tag-name.outputs.tagname }} -t "Documents" -n "Generated documents (${{ steps.tag-name.outputs.tagname }})"
          gh release upload ${{ steps.tag-name.outputs.tagname }} *.pdf
